version: '3.8'
services:
  web:
    build: .
    ports:
      - "8090:8000"
    environment:
      - DEBUG=True
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=ticket_booking
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: