# Generated by Django 4.2.7 on 2025-04-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='show',
            name='available_seats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='show',
            name='total_seats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='show',
            name='venue',
            field=models.CharField(max_length=100),
        ),
    ]
